// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: merchants.sql

package sqlcgen

import (
	"context"
	"time"
)

const createMerchant = `-- name: CreateMerchant :one
INSERT INTO merchants (id, name, document_number, email, status, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, name, document_number, email, status, created_at, updated_at
`

type CreateMerchantParams struct {
	ID             string
	Name           string
	DocumentNumber string
	Email          string
	Status         string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

func (q *Queries) CreateMerchant(ctx context.Context, arg CreateMerchantParams) (Merchant, error) {
	row := q.db.QueryRowContext(ctx, createMerchant,
		arg.ID,
		arg.Name,
		arg.DocumentNumber,
		arg.Email,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Merchant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DocumentNumber,
		&i.Email,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMerchantByID = `-- name: GetMerchantByID :one
SELECT id, name, document_number, email, status, created_at, updated_at FROM merchants
WHERE id = $1
`

func (q *Queries) GetMerchantByID(ctx context.Context, id string) (Merchant, error) {
	row := q.db.QueryRowContext(ctx, getMerchantByID, id)
	var i Merchant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DocumentNumber,
		&i.Email,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
