// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"database/sql"
	"time"

	"github.com/shopspring/decimal"
)

type Merchant struct {
	ID             string
	Name           string
	DocumentNumber string
	Email          string
	Status         string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type Payment struct {
	ID                string
	MerchantID        string
	ExternalReference string
	Amount            decimal.Decimal
	Currency          string
	PaymentMethod     string
	Status            string
	IdempotencyKey    string
	CreatedAt         time.Time
	UpdatedAt         time.Time
	ProviderReference sql.NullString
	ProviderName      sql.NullString
}

type PaymentStatusHistory struct {
	ID             string
	PaymentID      string
	PreviousStatus sql.NullString
	NewStatus      string
	Reason         sql.NullString
	ChangedBy      sql.NullString
	CreatedAt      time.Time
}
