// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payments.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const countPayments = `-- name: CountPayments :one
SELECT count(*) FROM payments
WHERE ($1::uuid IS NULL OR merchant_id = $1)
  AND ($2::text IS NULL OR status = $2)
  AND ($3::text IS NULL OR payment_method = $3)
  AND ($4::timestamptz IS NULL OR created_at >= $4)
  AND ($5::timestamptz IS NULL OR created_at <= $5)
`

type CountPaymentsParams struct {
	MerchantID    uuid.NullUUID
	Status        sql.NullString
	PaymentMethod sql.NullString
	DateFrom      sql.NullTime
	DateTo        sql.NullTime
}

func (q *Queries) CountPayments(ctx context.Context, arg CountPaymentsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPayments,
		arg.MerchantID,
		arg.Status,
		arg.PaymentMethod,
		arg.DateFrom,
		arg.DateTo,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPayment = `-- name: CreatePayment :one
INSERT INTO payments (
    id, merchant_id, external_reference, amount, currency,
    payment_method, status, idempotency_key, created_at, updated_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, merchant_id, external_reference, amount, currency, payment_method, status, idempotency_key, created_at, updated_at, provider_reference, provider_name
`

type CreatePaymentParams struct {
	ID                string
	MerchantID        string
	ExternalReference string
	Amount            decimal.Decimal
	Currency          string
	PaymentMethod     string
	Status            string
	IdempotencyKey    string
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error) {
	row := q.db.QueryRowContext(ctx, createPayment,
		arg.ID,
		arg.MerchantID,
		arg.ExternalReference,
		arg.Amount,
		arg.Currency,
		arg.PaymentMethod,
		arg.Status,
		arg.IdempotencyKey,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.ExternalReference,
		&i.Amount,
		&i.Currency,
		&i.PaymentMethod,
		&i.Status,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProviderReference,
		&i.ProviderName,
	)
	return i, err
}

const getMerchantSummary = `-- name: GetMerchantSummary :one
SELECT
    count(*) AS total_payments,
    count(*) FILTER (WHERE status = 'APPROVED') AS approved_payments,
    count(*) FILTER (WHERE status = 'REJECTED') AS rejected_payments,
    count(*) FILTER (WHERE status = 'PENDING') AS pending_payments,
    COALESCE(sum(amount) FILTER (WHERE status = 'APPROVED'), 0)::numeric AS approved_amount
FROM payments
WHERE merchant_id = $1
`

type GetMerchantSummaryRow struct {
	TotalPayments    int64
	ApprovedPayments int64
	RejectedPayments int64
	PendingPayments  int64
	ApprovedAmount   decimal.Decimal
}

func (q *Queries) GetMerchantSummary(ctx context.Context, merchantID string) (GetMerchantSummaryRow, error) {
	row := q.db.QueryRowContext(ctx, getMerchantSummary, merchantID)
	var i GetMerchantSummaryRow
	err := row.Scan(
		&i.TotalPayments,
		&i.ApprovedPayments,
		&i.RejectedPayments,
		&i.PendingPayments,
		&i.ApprovedAmount,
	)
	return i, err
}

const getPaymentByID = `-- name: GetPaymentByID :one
SELECT id, merchant_id, external_reference, amount, currency, payment_method, status, idempotency_key, created_at, updated_at, provider_reference, provider_name FROM payments
WHERE id = $1
`

func (q *Queries) GetPaymentByID(ctx context.Context, id string) (Payment, error) {
	row := q.db.QueryRowContext(ctx, getPaymentByID, id)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.ExternalReference,
		&i.Amount,
		&i.Currency,
		&i.PaymentMethod,
		&i.Status,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProviderReference,
		&i.ProviderName,
	)
	return i, err
}

const getPaymentByIdempotencyKey = `-- name: GetPaymentByIdempotencyKey :one
SELECT id, merchant_id, external_reference, amount, currency, payment_method, status, idempotency_key, created_at, updated_at, provider_reference, provider_name FROM payments
WHERE idempotency_key = $1
`

func (q *Queries) GetPaymentByIdempotencyKey(ctx context.Context, idempotencyKey string) (Payment, error) {
	row := q.db.QueryRowContext(ctx, getPaymentByIdempotencyKey, idempotencyKey)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.ExternalReference,
		&i.Amount,
		&i.Currency,
		&i.PaymentMethod,
		&i.Status,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProviderReference,
		&i.ProviderName,
	)
	return i, err
}

const getPaymentByMerchantAndExternalReference = `-- name: GetPaymentByMerchantAndExternalReference :one
SELECT id, merchant_id, external_reference, amount, currency, payment_method, status, idempotency_key, created_at, updated_at, provider_reference, provider_name FROM payments
WHERE merchant_id = $1 AND external_reference = $2
`

type GetPaymentByMerchantAndExternalReferenceParams struct {
	MerchantID        string
	ExternalReference string
}

func (q *Queries) GetPaymentByMerchantAndExternalReference(ctx context.Context, arg GetPaymentByMerchantAndExternalReferenceParams) (Payment, error) {
	row := q.db.QueryRowContext(ctx, getPaymentByMerchantAndExternalReference, arg.MerchantID, arg.ExternalReference)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.ExternalReference,
		&i.Amount,
		&i.Currency,
		&i.PaymentMethod,
		&i.Status,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProviderReference,
		&i.ProviderName,
	)
	return i, err
}

const listPayments = `-- name: ListPayments :many
SELECT id, merchant_id, external_reference, amount, currency, payment_method, status, idempotency_key, created_at, updated_at, provider_reference, provider_name FROM payments
WHERE ($1::uuid IS NULL OR merchant_id = $1)
  AND ($2::text IS NULL OR status = $2)
  AND ($3::text IS NULL OR payment_method = $3)
  AND ($4::timestamptz IS NULL OR created_at >= $4)
  AND ($5::timestamptz IS NULL OR created_at <= $5)
ORDER BY created_at DESC
LIMIT $7 OFFSET $6
`

type ListPaymentsParams struct {
	MerchantID    uuid.NullUUID
	Status        sql.NullString
	PaymentMethod sql.NullString
	DateFrom      sql.NullTime
	DateTo        sql.NullTime
	PageOffset    int32
	PageLimit     int32
}

func (q *Queries) ListPayments(ctx context.Context, arg ListPaymentsParams) ([]Payment, error) {
	rows, err := q.db.QueryContext(ctx, listPayments,
		arg.MerchantID,
		arg.Status,
		arg.PaymentMethod,
		arg.DateFrom,
		arg.DateTo,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Payment
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.ID,
			&i.MerchantID,
			&i.ExternalReference,
			&i.Amount,
			&i.Currency,
			&i.PaymentMethod,
			&i.Status,
			&i.IdempotencyKey,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProviderReference,
			&i.ProviderName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markPaymentProcessing = `-- name: MarkPaymentProcessing :one
UPDATE payments
SET status = 'PROCESSING', provider_reference = $2, provider_name = $3, updated_at = $4
WHERE id = $1
RETURNING id, merchant_id, external_reference, amount, currency, payment_method, status, idempotency_key, created_at, updated_at, provider_reference, provider_name
`

type MarkPaymentProcessingParams struct {
	ID                string
	ProviderReference sql.NullString
	ProviderName      sql.NullString
	UpdatedAt         time.Time
}

// Guarda a qué proveedor se envió (provider_name), la referencia de esa
// operación (provider_reference), y el paso a PROCESSING, en una sola
// escritura ANTES de llamar al proveedor externo: si el proceso se cae
// justo después de esta escritura y antes de recibir la respuesta del
// proveedor, ya queda todo lo necesario guardado para poder conciliar
// luego (incluyendo con cuál proveedor había que conciliar).
func (q *Queries) MarkPaymentProcessing(ctx context.Context, arg MarkPaymentProcessingParams) (Payment, error) {
	row := q.db.QueryRowContext(ctx, markPaymentProcessing,
		arg.ID,
		arg.ProviderReference,
		arg.ProviderName,
		arg.UpdatedAt,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.ExternalReference,
		&i.Amount,
		&i.Currency,
		&i.PaymentMethod,
		&i.Status,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProviderReference,
		&i.ProviderName,
	)
	return i, err
}

const updatePaymentStatus = `-- name: UpdatePaymentStatus :one
UPDATE payments
SET status = $2, updated_at = $3
WHERE id = $1
RETURNING id, merchant_id, external_reference, amount, currency, payment_method, status, idempotency_key, created_at, updated_at, provider_reference, provider_name
`

type UpdatePaymentStatusParams struct {
	ID        string
	Status    string
	UpdatedAt time.Time
}

func (q *Queries) UpdatePaymentStatus(ctx context.Context, arg UpdatePaymentStatusParams) (Payment, error) {
	row := q.db.QueryRowContext(ctx, updatePaymentStatus, arg.ID, arg.Status, arg.UpdatedAt)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.ExternalReference,
		&i.Amount,
		&i.Currency,
		&i.PaymentMethod,
		&i.Status,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProviderReference,
		&i.ProviderName,
	)
	return i, err
}
