// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payment_status_history.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"time"
)

const createPaymentStatusHistory = `-- name: CreatePaymentStatusHistory :one
INSERT INTO payment_status_history (id, payment_id, previous_status, new_status, reason, changed_by, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, payment_id, previous_status, new_status, reason, changed_by, created_at
`

type CreatePaymentStatusHistoryParams struct {
	ID             string
	PaymentID      string
	PreviousStatus sql.NullString
	NewStatus      string
	Reason         sql.NullString
	ChangedBy      sql.NullString
	CreatedAt      time.Time
}

func (q *Queries) CreatePaymentStatusHistory(ctx context.Context, arg CreatePaymentStatusHistoryParams) (PaymentStatusHistory, error) {
	row := q.db.QueryRowContext(ctx, createPaymentStatusHistory,
		arg.ID,
		arg.PaymentID,
		arg.PreviousStatus,
		arg.NewStatus,
		arg.Reason,
		arg.ChangedBy,
		arg.CreatedAt,
	)
	var i PaymentStatusHistory
	err := row.Scan(
		&i.ID,
		&i.PaymentID,
		&i.PreviousStatus,
		&i.NewStatus,
		&i.Reason,
		&i.ChangedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listPaymentStatusHistoryByPaymentID = `-- name: ListPaymentStatusHistoryByPaymentID :many
SELECT id, payment_id, previous_status, new_status, reason, changed_by, created_at FROM payment_status_history
WHERE payment_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListPaymentStatusHistoryByPaymentID(ctx context.Context, paymentID string) ([]PaymentStatusHistory, error) {
	rows, err := q.db.QueryContext(ctx, listPaymentStatusHistoryByPaymentID, paymentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PaymentStatusHistory
	for rows.Next() {
		var i PaymentStatusHistory
		if err := rows.Scan(
			&i.ID,
			&i.PaymentID,
			&i.PreviousStatus,
			&i.NewStatus,
			&i.Reason,
			&i.ChangedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
