// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payments.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/shopspring/decimal"
)

const createPayment = `-- name: CreatePayment :one
INSERT INTO payments (
    id, merchant_id, external_reference, amount, currency,
    payment_method, status, idempotency_key, created_at, updated_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, merchant_id, external_reference, amount, currency, payment_method, status, idempotency_key, created_at, updated_at
`

type CreatePaymentParams struct {
	ID                string
	MerchantID        string
	ExternalReference string
	Amount            decimal.Decimal
	Currency          string
	PaymentMethod     string
	Status            string
	IdempotencyKey    string
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error) {
	row := q.db.QueryRowContext(ctx, createPayment,
		arg.ID,
		arg.MerchantID,
		arg.ExternalReference,
		arg.Amount,
		arg.Currency,
		arg.PaymentMethod,
		arg.Status,
		arg.IdempotencyKey,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.ExternalReference,
		&i.Amount,
		&i.Currency,
		&i.PaymentMethod,
		&i.Status,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentByID = `-- name: GetPaymentByID :one
SELECT id, merchant_id, external_reference, amount, currency, payment_method, status, idempotency_key, created_at, updated_at FROM payments
WHERE id = $1
`

func (q *Queries) GetPaymentByID(ctx context.Context, id string) (Payment, error) {
	row := q.db.QueryRowContext(ctx, getPaymentByID, id)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.ExternalReference,
		&i.Amount,
		&i.Currency,
		&i.PaymentMethod,
		&i.Status,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentByIdempotencyKey = `-- name: GetPaymentByIdempotencyKey :one
SELECT id, merchant_id, external_reference, amount, currency, payment_method, status, idempotency_key, created_at, updated_at FROM payments
WHERE idempotency_key = $1
`

func (q *Queries) GetPaymentByIdempotencyKey(ctx context.Context, idempotencyKey string) (Payment, error) {
	row := q.db.QueryRowContext(ctx, getPaymentByIdempotencyKey, idempotencyKey)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.ExternalReference,
		&i.Amount,
		&i.Currency,
		&i.PaymentMethod,
		&i.Status,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentByMerchantAndExternalReference = `-- name: GetPaymentByMerchantAndExternalReference :one
SELECT id, merchant_id, external_reference, amount, currency, payment_method, status, idempotency_key, created_at, updated_at FROM payments
WHERE merchant_id = $1 AND external_reference = $2
`

type GetPaymentByMerchantAndExternalReferenceParams struct {
	MerchantID        string
	ExternalReference string
}

func (q *Queries) GetPaymentByMerchantAndExternalReference(ctx context.Context, arg GetPaymentByMerchantAndExternalReferenceParams) (Payment, error) {
	row := q.db.QueryRowContext(ctx, getPaymentByMerchantAndExternalReference, arg.MerchantID, arg.ExternalReference)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.ExternalReference,
		&i.Amount,
		&i.Currency,
		&i.PaymentMethod,
		&i.Status,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePaymentStatus = `-- name: UpdatePaymentStatus :one
UPDATE payments
SET status = $2, updated_at = $3
WHERE id = $1
RETURNING id, merchant_id, external_reference, amount, currency, payment_method, status, idempotency_key, created_at, updated_at
`

type UpdatePaymentStatusParams struct {
	ID        string
	Status    string
	UpdatedAt time.Time
}

func (q *Queries) UpdatePaymentStatus(ctx context.Context, arg UpdatePaymentStatusParams) (Payment, error) {
	row := q.db.QueryRowContext(ctx, updatePaymentStatus, arg.ID, arg.Status, arg.UpdatedAt)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.ExternalReference,
		&i.Amount,
		&i.Currency,
		&i.PaymentMethod,
		&i.Status,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
