// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"context"
)

type Querier interface {
	CountPayments(ctx context.Context, arg CountPaymentsParams) (int64, error)
	CreateMerchant(ctx context.Context, arg CreateMerchantParams) (Merchant, error)
	CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error)
	CreatePaymentStatusHistory(ctx context.Context, arg CreatePaymentStatusHistoryParams) (PaymentStatusHistory, error)
	GetMerchantByID(ctx context.Context, id string) (Merchant, error)
	GetMerchantSummary(ctx context.Context, merchantID string) (GetMerchantSummaryRow, error)
	GetPaymentByID(ctx context.Context, id string) (Payment, error)
	GetPaymentByIdempotencyKey(ctx context.Context, idempotencyKey string) (Payment, error)
	GetPaymentByMerchantAndExternalReference(ctx context.Context, arg GetPaymentByMerchantAndExternalReferenceParams) (Payment, error)
	ListPaymentStatusHistoryByPaymentID(ctx context.Context, paymentID string) ([]PaymentStatusHistory, error)
	ListPayments(ctx context.Context, arg ListPaymentsParams) ([]Payment, error)
	// Guarda a qué proveedor se envió (provider_name), la referencia de esa
	// operación (provider_reference), y el paso a PROCESSING, en una sola
	// escritura ANTES de llamar al proveedor externo: si el proceso se cae
	// justo después de esta escritura y antes de recibir la respuesta del
	// proveedor, ya queda todo lo necesario guardado para poder conciliar
	// luego (incluyendo con cuál proveedor había que conciliar).
	MarkPaymentProcessing(ctx context.Context, arg MarkPaymentProcessingParams) (Payment, error)
	UpdatePaymentStatus(ctx context.Context, arg UpdatePaymentStatusParams) (Payment, error)
}

var _ Querier = (*Queries)(nil)
